"""add boss xp reward

Revision ID: c1fa900290bb
Revises: c9c7d9fcca81
Create Date: 2026-09-25 10:33:24.437069
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fa900290bb'
down_revision: Union[str, Sequence[str], None] = 'c9c7d9fcca81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_fights', sa.Column('xp_reward', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_fights', 'xp_reward')
    # ### end Alembic commands ###
