"""add boss damage to quests

Revision ID: c9c7d9fcca81
Revises: 52bd00f4a2c7
Create Date: 2026-09-25 10:31:22.965973
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c7d9fcca81'
down_revision: Union[str, Sequence[str], None] = '52bd00f4a2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('boss_damage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'boss_damage')
    # ### end Alembic commands ###
